version: '3'

services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - rabbitmq

  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - rabbitmq

  product_service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
