global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['auth_service:5001', 'product_service:5002', 'order_service:5003']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
